// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIRNfHtOByKqW_Y1gpzlDL9GZuj2p6sx0',
    appId: '1:318510990337:web:5a5446f1610785d4f06c00',
    messagingSenderId: '318510990337',
    projectId: 'swift-chat-ba90f',
    authDomain: 'swift-chat-ba90f.firebaseapp.com',
    storageBucket: 'swift-chat-ba90f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxMU64glQZNdbNNSVvl2Kdi7I4fmN5b-M',
    appId: '1:318510990337:android:54aa401392fc458ff06c00',
    messagingSenderId: '318510990337',
    projectId: 'swift-chat-ba90f',
    storageBucket: 'swift-chat-ba90f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCRa1oL0QydENhSL-17wK7otpE_tXp_o0',
    appId: '1:318510990337:ios:7d4275f095dca5eef06c00',
    messagingSenderId: '318510990337',
    projectId: 'swift-chat-ba90f',
    storageBucket: 'swift-chat-ba90f.firebasestorage.app',
    iosBundleId: 'me.ritom.swiftChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCRa1oL0QydENhSL-17wK7otpE_tXp_o0',
    appId: '1:318510990337:ios:7d4275f095dca5eef06c00',
    messagingSenderId: '318510990337',
    projectId: 'swift-chat-ba90f',
    storageBucket: 'swift-chat-ba90f.firebasestorage.app',
    iosBundleId: 'me.ritom.swiftChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIRNfHtOByKqW_Y1gpzlDL9GZuj2p6sx0',
    appId: '1:318510990337:web:bfa646864da4a360f06c00',
    messagingSenderId: '318510990337',
    projectId: 'swift-chat-ba90f',
    authDomain: 'swift-chat-ba90f.firebaseapp.com',
    storageBucket: 'swift-chat-ba90f.firebasestorage.app',
  );
}
